name: Deploy to Chabokan
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Chabokan CLI
        run: npm install -g @chabokan.net/cli
      - name: Deploy to Chabokan
        env:
          CHABOKAN_TOKEN: ${{ secrets.CHABOKAN_TOKEN }}
        run: |
          chabok login -t $CHABOKAN_TOKEN
          chabok deploy -s nodejs-sm6tdl --path .